<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Place;

class PlaceSeeder extends Seeder
{
    public function run()
    {
        Place::insert([
            [
                'name' => 'Statue of Liberty',
                'desc' => 'Biểu tượng tự do tại New York.',
                'address' => 'Liberty Island, New York, NY, USA',
                'country' => 'USA',
                'tag' => 'lịch sử, biểu tượng',
                'lat' => 40.6892,
                'lon' => -74.0445,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Grand Canyon',
                'desc' => 'Hẻm núi vĩ đại với cảnh quan ngoạn mục.',
                'address' => 'Grand Canyon, Arizona, USA',
                'country' => 'USA',
                'tag' => 'thiên nhiên, cảnh đẹp',
                'lat' => 36.1069,
                'lon' => -112.1129,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yellowstone National Park',
                'desc' => 'Công viên quốc gia đầu tiên trên thế giới.',
                'address' => 'Wyoming, Montana, Idaho, USA',
                'country' => 'USA',
                'tag' => 'thiên nhiên, động vật hoang dã',
                'lat' => 44.4280,
                'lon' => -110.5885,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Times Square',
                'desc' => 'Khu trung tâm sôi động bậc nhất của New York.',
                'address' => 'Manhattan, NY 10036, USA',
                'country' => 'USA',
                'tag' => 'mua sắm, giải trí',
                'lat' => 40.7580,
                'lon' => -73.9855,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Golden Gate Bridge',
                'desc' => 'Cây cầu nổi tiếng ở San Francisco.',
                'address' => 'San Francisco, CA, USA',
                'country' => 'USA',
                'tag' => 'biểu tượng, kiến trúc',
                'lat' => 37.8199,
                'lon' => -122.4783,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Niagara Falls',
                'desc' => 'Thác nước nổi tiếng giữa Mỹ và Canada.',
                'address' => 'Niagara Falls, NY, USA',
                'country' => 'USA',
                'tag' => 'thiên nhiên, thác nước',
                'lat' => 43.0962,
                'lon' => -79.0377,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Disneyland',
                'desc' => 'Công viên giải trí nổi tiếng ở California.',
                'address' => 'Anaheim, CA, USA',
                'country' => 'USA',
                'tag' => 'gia đình, vui chơi',
                'lat' => 33.8121,
                'lon' => -117.9190,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Walt Disney World',
                'desc' => 'Tổ hợp giải trí lớn nhất tại Orlando.',
                'address' => 'Orlando, FL, USA',
                'country' => 'USA',
                'tag' => 'vui chơi, giải trí',
                'lat' => 28.3852,
                'lon' => -81.5639,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Hollywood Sign',
                'desc' => 'Biểu tượng điện ảnh nổi tiếng tại Los Angeles.',
                'address' => 'Los Angeles, CA, USA',
                'country' => 'USA',
                'tag' => 'điện ảnh, biểu tượng',
                'lat' => 34.1341,
                'lon' => -118.3215,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Las Vegas Strip',
                'desc' => 'Khu giải trí và sòng bạc nổi tiếng.',
                'address' => 'Las Vegas, NV, USA',
                'country' => 'USA',
                'tag' => 'giải trí, casino',
                'lat' => 36.1147,
                'lon' => -115.1728,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Mount Rushmore',
                'desc' => 'Tượng khắc 4 tổng thống Mỹ trên núi đá.',
                'address' => 'Keystone, SD, USA',
                'country' => 'USA',
                'tag' => 'lịch sử, tượng đài',
                'lat' => 43.8791,
                'lon' => -103.4591,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Central Park',
                'desc' => 'Công viên lớn ở trung tâm Manhattan.',
                'address' => 'New York, NY, USA',
                'country' => 'USA',
                'tag' => 'thiên nhiên, thư giãn',
                'lat' => 40.7851,
                'lon' => -73.9683,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Alcatraz Island',
                'desc' => 'Hòn đảo từng là nhà tù nổi tiếng.',
                'address' => 'San Francisco, CA, USA',
                'country' => 'USA',
                'tag' => 'lịch sử, đảo',
                'lat' => 37.8267,
                'lon' => -122.4230,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'The White House',
                'desc' => 'Dinh tổng thống Hoa Kỳ.',
                'address' => '1600 Pennsylvania Ave NW, Washington, DC, USA',
                'country' => 'USA',
                'tag' => 'chính trị, biểu tượng',
                'lat' => 38.8977,
                'lon' => -77.0365,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'The Pentagon',
                'desc' => 'Trụ sở Bộ Quốc phòng Mỹ.',
                'address' => 'Arlington, VA, USA',
                'country' => 'USA',
                'tag' => 'chính phủ, quân sự',
                'lat' => 38.8719,
                'lon' => -77.0563,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Brooklyn Bridge',
                'desc' => 'Cầu cổ nối Manhattan và Brooklyn.',
                'address' => 'New York, NY, USA',
                'country' => 'USA',
                'tag' => 'kiến trúc, lịch sử',
                'lat' => 40.7061,
                'lon' => -73.9969,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Universal Studios Hollywood',
                'desc' => 'Công viên giải trí với chủ đề phim ảnh.',
                'address' => 'Los Angeles, CA, USA',
                'country' => 'USA',
                'tag' => 'vui chơi, điện ảnh',
                'lat' => 34.1381,
                'lon' => -118.3534,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Bryce Canyon National Park',
                'desc' => 'Công viên nổi tiếng với đá đỏ và cảnh quan độc đáo.',
                'address' => 'Utah, USA',
                'country' => 'USA',
                'tag' => 'thiên nhiên, núi đá',
                'lat' => 37.5930,
                'lon' => -112.1871,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Space Needle',
                'desc' => 'Tháp quan sát biểu tượng của Seattle.',
                'address' => 'Seattle, WA, USA',
                'country' => 'USA',
                'tag' => 'kiến trúc, biểu tượng',
                'lat' => 47.6205,
                'lon' => -122.3493,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Boston Freedom Trail',
                'desc' => 'Đường mòn lịch sử ở trung tâm Boston.',
                'address' => 'Boston, MA, USA',
                'country' => 'USA',
                'tag' => 'lịch sử, tham quan',
                'lat' => 42.3554,
                'lon' => -71.0605,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'CN Tower',
                'desc' => 'Tháp truyền hình nổi tiếng tại Toronto.',
                'address' => 'Toronto, ON, Canada',
                'country' => 'Canada',
                'tag' => 'kiến trúc, biểu tượng',
                'lat' => 43.6426,
                'lon' => -79.3871,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Niagara Falls',
                'desc' => 'Thác nước nổi tiếng giữa Canada và Mỹ.',
                'address' => 'Niagara Falls, ON, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, thác nước',
                'lat' => 43.0896,
                'lon' => -79.0849,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Banff National Park',
                'desc' => 'Công viên quốc gia nổi tiếng ở Alberta.',
                'address' => 'Banff, AB, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, núi non',
                'lat' => 51.4968,
                'lon' => -115.9281,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Lake Louise',
                'desc' => 'Hồ nước tuyệt đẹp với màu xanh ngọc.',
                'address' => 'Lake Louise, AB, Canada',
                'country' => 'Canada',
                'tag' => 'hồ, thiên nhiên',
                'lat' => 51.4169,
                'lon' => -116.2156,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Old Quebec',
                'desc' => 'Khu phố cổ được UNESCO công nhận.',
                'address' => 'Quebec City, QC, Canada',
                'country' => 'Canada',
                'tag' => 'lịch sử, di sản',
                'lat' => 46.8139,
                'lon' => -71.2082,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Parliament Hill',
                'desc' => 'Trụ sở Quốc hội Canada tại Ottawa.',
                'address' => 'Ottawa, ON, Canada',
                'country' => 'Canada',
                'tag' => 'chính trị, kiến trúc',
                'lat' => 45.4236,
                'lon' => -75.7009,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Capilano Suspension Bridge',
                'desc' => 'Cây cầu treo nổi tiếng ở Vancouver.',
                'address' => 'Vancouver, BC, Canada',
                'country' => 'Canada',
                'tag' => 'phiêu lưu, thiên nhiên',
                'lat' => 49.3429,
                'lon' => -123.1149,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Gros Morne National Park',
                'desc' => 'Di sản thiên nhiên thế giới ở Newfoundland.',
                'address' => 'Newfoundland and Labrador, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, di sản',
                'lat' => 49.6499,
                'lon' => -57.7553,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Stanley Park',
                'desc' => 'Công viên đô thị nổi tiếng ở Vancouver.',
                'address' => 'Vancouver, BC, Canada',
                'country' => 'Canada',
                'tag' => 'công viên, thư giãn',
                'lat' => 49.3043,
                'lon' => -123.1443,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Whistler Blackcomb',
                'desc' => 'Khu nghỉ dưỡng trượt tuyết hàng đầu.',
                'address' => 'Whistler, BC, Canada',
                'country' => 'Canada',
                'tag' => 'trượt tuyết, nghỉ dưỡng',
                'lat' => 50.1150,
                'lon' => -122.9472,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Toronto Islands',
                'desc' => 'Quần đảo ngoài khơi thành phố Toronto.',
                'address' => 'Toronto, ON, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, thư giãn',
                'lat' => 43.6204,
                'lon' => -79.3789,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Mont Tremblant',
                'desc' => 'Khu du lịch trượt tuyết tại Quebec.',
                'address' => 'Mont Tremblant, QC, Canada',
                'country' => 'Canada',
                'tag' => 'thể thao, trượt tuyết',
                'lat' => 46.2108,
                'lon' => -74.5846,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Hopewell Rocks',
                'desc' => 'Những khối đá nổi tiếng ở vịnh Fundy.',
                'address' => 'New Brunswick, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, độc đáo',
                'lat' => 45.8281,
                'lon' => -64.5772,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Royal Ontario Museum',
                'desc' => 'Bảo tàng lớn nhất Canada về lịch sử và khoa học.',
                'address' => 'Toronto, ON, Canada',
                'country' => 'Canada',
                'tag' => 'bảo tàng, giáo dục',
                'lat' => 43.6677,
                'lon' => -79.3948,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Peggy’s Cove',
                'desc' => 'Ngôi làng chài cổ kính với ngọn hải đăng nổi tiếng.',
                'address' => 'Nova Scotia, Canada',
                'country' => 'Canada',
                'tag' => 'làng chài, hải đăng',
                'lat' => 44.4939,
                'lon' => -63.9158,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'The Butchart Gardens',
                'desc' => 'Khu vườn nổi tiếng với nhiều loại hoa và thiết kế cảnh quan.',
                'address' => 'Brentwood Bay, BC, Canada',
                'country' => 'Canada',
                'tag' => 'hoa, công viên',
                'lat' => 48.5647,
                'lon' => -123.4662,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Canadian Museum of History',
                'desc' => 'Bảo tàng về lịch sử và văn hóa Canada.',
                'address' => 'Gatineau, QC, Canada',
                'country' => 'Canada',
                'tag' => 'bảo tàng, lịch sử',
                'lat' => 45.4292,
                'lon' => -75.7081,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Kensington Market',
                'desc' => 'Khu chợ văn hóa sôi động ở trung tâm Toronto.',
                'address' => 'Toronto, ON, Canada',
                'country' => 'Canada',
                'tag' => 'văn hóa, chợ',
                'lat' => 43.6555,
                'lon' => -79.4056,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Rideau Canal',
                'desc' => 'Kênh đào lâu đời, trượt băng nổi tiếng vào mùa đông.',
                'address' => 'Ottawa, ON, Canada',
                'country' => 'Canada',
                'tag' => 'di sản, mùa đông',
                'lat' => 45.4215,
                'lon' => -75.6993,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Prince Edward Island National Park',
                'desc' => 'Công viên nổi tiếng với bãi biển cát đỏ và cảnh quan thiên nhiên.',
                'address' => 'Prince Edward Island, Canada',
                'country' => 'Canada',
                'tag' => 'thiên nhiên, bãi biển',
                'lat' => 46.4151,
                'lon' => -63.1352,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
