<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tours')->insert([
            [
                'name' => 'Hạ Long Bay Adventure',
                'desc' => 'Explore the stunning beauty of Hạ Long Bay.',
                'location' => 'Hạ Long',
                'start_date' => '2025-06-01',
                'end_date' => '2025-06-05',
                'price' => 500.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour mạo hiểm', 'Tour thiên nhiên']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phú Quốc Island Getaway',
                'desc' => 'Relax on the pristine beaches of Phú Quốc.',
                'location' => 'Phú Quốc',
                'start_date' => '2025-07-10',
                'end_date' => '2025-07-15',
                'price' => 700.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour nghỉ dưỡng']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Đà Lạt Nature Retreat',
                'desc' => 'Enjoy the cool weather and scenic views of Đà Lạt.',
                'location' => 'Đà Lạt',
                'start_date' => '2025-08-20',
                'end_date' => '2025-08-25',
                'price' => 400.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour thiên nhiên']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sapa Trekking Tour',
                'desc' => 'Experience the breathtaking landscapes of Sapa.',
                'location' => 'Sapa',
                'start_date' => '2025-09-05',
                'end_date' => '2025-09-10',
                'price' => 600.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour trekking']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mekong Delta Cruise',
                'desc' => 'Discover the beauty of the Mekong Delta.',
                'location' => 'Mekong Delta',
                'start_date' => '2025-10-15',
                'end_date' => '2025-10-20',
                'price' => 550.00,
                'is_featured' => true, 
                'types' => json_encode(['Tour trong nước', 'Tour du thuyền']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nha Trang Beach Escape',
                'desc' => 'Enjoy the sun and sea in Nha Trang.',
                'location' => 'Nha Trang',
                'start_date' => '2025-11-01',
                'end_date' => '2025-11-05',
                'price' => 650.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour biển']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hội An Ancient Town Tour',
                'desc' => 'Explore the charming streets of Hội An.',
                'location' => 'Hội An',
                'start_date' => '2025-12-10',
                'end_date' => '2025-12-15',
                'price' => 450.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour văn hóa']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phong Nha Cave Expedition',
                'desc' => 'Discover the wonders of Phong Nha caves.',
                'location' => 'Phong Nha',
                'start_date' => '2025-12-20',
                'end_date' => '2025-12-25',
                'price' => 500.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour khám phá']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hà Giang Loop Adventure',
                'desc' => 'Experience the stunning landscapes of Hà Giang.',
                'location' => 'Hà Giang',
                'start_date' => '2026-01-05',
                'end_date' => '2026-01-10',
                'price' => 700.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour mạo hiểm']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cát Bà Island Tour',
                'desc' => 'Explore the natural beauty of Cát Bà Island.',
                'location' => 'Cát Bà',
                'start_date' => '2026-02-15',
                'end_date' => '2026-02-20',
                'price' => 600.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour sinh thái']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mai Châu Valley Tour',
                'desc' => 'Experience the culture and nature of Mai Châu.',
                'location' => 'Mai Châu',
                'start_date' => '2026-03-01',
                'end_date' => '2026-03-05',
                'price' => 550.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour văn hóa']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Côn Đảo Island Tour',
                'desc' => 'Discover the history and beauty of Côn Đảo.',
                'location' => 'Côn Đảo',
                'start_date' => '2026-04-10',
                'end_date' => '2026-04-15',
                'price' => 800.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour lịch sử']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bà Nà Hills Tour',
                'desc' => 'Enjoy the stunning views from Bà Nà Hills.',
                'location' => 'Bà Nà',
                'start_date' => '2026-05-20',
                'end_date' => '2026-05-25',
                'price' => 400.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour núi']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sa Pa Cultural Experience',
                'desc' => 'Immerse yourself in the culture of Sa Pa.',
                'location' => 'Sa Pa',
                'start_date' => '2026-06-01',
                'end_date' => '2026-06-05',
                'price' => 600.00,
                'is_featured' => false,
                'types' => json_encode(['Tour trong nước', 'Tour văn hóa']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ninh Bình Eco Tour',
                'desc' => 'Explore the natural beauty of Ninh Bình.',
                'location' => 'Ninh Bình',
                'start_date' => '2026-07-10',
                'end_date' => '2026-07-15',
                'price' => 500.00,
                'is_featured' => true,
                'types' => json_encode(['Tour trong nước', 'Tour sinh thái']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
    }
}